### ISSUE TITLE
mail schedule: traceback

### ISSUE THREAD

**Issue by markvdb** [jrial/fosdem-volunteers#29]
http://dpaste.com/1RWE82T

**Comment by jrial** [comment]
Woops, embarassing... Try again, and close ticket if the problem is solved (I'm at work, so I can't spend too much time on this).

**Comment by markvdb** [comment]
Alas...

http://dpaste.com/2E8C2HF

2015-01-19 12:13 GMT+01:00 Juan Rial <notifications@github.com>:

> Woops, embarassing... Try again, and close ticket if the problem is solved
> (I'm at work, so I can't spend too much time on this).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jrial/fosdem-volunteers/issues/29#issuecomment-70477944>
> .
>



-- 
Mark Van den Borre
Hogestraat 16
3000 Leuven, België
+32 486 961726

**Comment by markvdb** [comment]
http://dpaste.com/09Q6EKN

2015-01-19 12:16 GMT+01:00 Mark Van den Borre <mark@markvdb.be>:

> Alas...
>
> http://dpaste.com/2E8C2HF
>
> 2015-01-19 12:13 GMT+01:00 Juan Rial <notifications@github.com>:
>
>> Woops, embarassing... Try again, and close ticket if the problem is
>> solved (I'm at work, so I can't spend too much time on this).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jrial/fosdem-volunteers/issues/29#issuecomment-70477944>
>> .
>>
>
>
>
> --
> Mark Van den Borre
> Hogestraat 16
> 3000 Leuven, België
> +32 486 961726
>



-- 
Mark Van den Borre
Hogestraat 16
3000 Leuven, België
+32 486 961726

**Comment by markvdb** [comment]
Working now. Thx for the quick fix.
