### ISSUE TITLE
https://volunteers.fosdem.org/volunteers/$user/edit/ should contain the mugshot

### ISSUE THREAD

**Issue by RichiH** [jrial/fosdem-volunteers#32]
In `edit details`, it should show the mugshot as well.

**Comment by silps** [comment]
done
https://github.com/jrial/fosdem-volunteers/blob/master/volunteers/templates/userena/profile_form.html#L27

**Comment by jrial** [comment]
Reopening, as not deployed yet.

**Comment by jrial** [comment]
Deployed
