### ISSUE TITLE
Profile list could be case insensitive

### ISSUE THREAD

**Issue by AmethystWillow** [jrial/fosdem-volunteers#35]
It would be really helpful if the sorting of the profiles on the list pages could be case insensitive. As it is now profiles are shown alphabetically by first name, first the names entered with capitals, then a second set with uncapitalised names.

**Comment by silps** [comment]
done
https://github.com/jrial/fosdem-volunteers/blob/master/volunteers/views.py#L497-L498

**Comment by jrial** [comment]
Deployed
