### ISSUE TITLE
Mail schedule fails for users with non unicode characters in their names

### ISSUE THREAD

**Issue by AmethystWillow** [jrial/fosdem-volunteers#36]
When trying to mail this user his schedule: https://volunteers.fosdem.org/tasks/mikaz360 I received a Django Error:

> UnicodeDecodeError at /tasks/mikaz360
> 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
> Request Method:	POST
> Request URL:	https://volunteers.fosdem.org/tasks/mikaz360
> Django Version:	1.5.4
> Exception Type:	UnicodeDecodeError
> Exception Value:	
> 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
> Exception Location:	/home/jrial/fosdem-volunteers/volunteers/models.py in mail_schedule, line 489
> Python Executable:	/usr/bin/python
> Python Version:	2.7.3
> Python Path:	
> ['/home/jrial/fosdem-volunteers',
> '/usr/local/bin',
> '/home/jrial/fosdem-volunteers',
> '/usr/lib/python2.7',
> '/usr/lib/python2.7/plat-linux2',
> '/usr/lib/python2.7/lib-tk',
> '/usr/lib/python2.7/lib-old',
> '/usr/lib/python2.7/lib-dynload',
> '/usr/local/lib/python2.7/dist-packages',
> '/usr/local/lib/python2.7/dist-packages/PIL',
> '/usr/lib/python2.7/dist-packages',
> '/usr/lib/pymodules/python2.7']
> Server time:	Thu, 29 Jan 2015 20:05:04 +0100

**Comment by silps** [comment]
fixed
https://github.com/jrial/fosdem-volunteers/blob/master/volunteers/models.py#L478

**Comment by jrial** [comment]
Deployed
