### ISSUE TITLE
unable to add task to specific volunteer

### ISSUE THREAD

**Issue by markvdb** [jrial/fosdem-volunteers#59]
@jrial 

Can't add any tasks to https://volunteers.fosdem.org/admin/volunteers/volunteer/101/ .

This is one of our most active volunteers. He's had piles of tasks form the past. No problem with others. (Query) optimisation problem? In any case, this is urgent! The above volunteer is taking care of all of Janson video for Sunday...

**Comment by markvdb** [comment]
Jrial circumvented timeout for now by increasing it from default (30) to 90.

**Comment by jrial** [comment]
Preliminary examination shows it's likely related to Django's scaffolding, and inefficient DB use.

Will resolve itself when we overhaul the admin interface as a part of #48
